FORMAT: 1A

# POST /signup
Creating a new user

+ Request (application/json)

        {
          "email": "2@example.com",
          "password": "password",
          "userName": "test"
        }

+ Response 200 (application/json; charset=UTF-8)
