version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - migration
      - redis
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - "./tmp/data/db:/var/lib/mysql"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./tmp/data/redis:/data"
    command: --loglevel debug
