version: 2.1
jobs:
  tests:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    steps:
      - run:
          name: Setup earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/download/v0.6.1/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
            earthly bootstrap
            earthly --version
      - run:
          name: "Docker login"
          command: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - checkout
      - run:
          name: Run tests
          command: earthly -P --ci --push +test

workflows:
  tests:
    jobs:
      - tests
