version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/IzumiSy/go-cleanarchitecture
    steps:
      - checkout
      - run: make test
