version: 2.1
jobs:
  prepare:
    machine: true
    steps:
      - run:
          name: Setup earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/download/v0.6.1/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
            earthly bootstrap
            earthly --version
      - run:
          name: "Docker login"
          command: docker login --username "izumisy" --password "$DOCKERHUB_TOKEN"
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - earthly

  unit-test:
    machine: true
    steps:
      - attach_workspace:
          at: /usr/local/bin
      - checkout
      - run: earthly +unit-test

  integration-test:
    machine: true
    steps:
      - attach_workspace:
          at: /usr/local/bin
      - checkout
      - run: earthly -P --ci --push +integration-test

workflows:
  tests:
    jobs:
      - prepare
      - unit-test:
          requires:
            - prepare
      - integration-test:
          requires:
            - prepare
          filters:
            branches:
              only:
                - master
