version: 2.1
jobs:
  tests:
    machine: true
    steps:
      - run:
          name: install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: setup earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/download/v0.6.1/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
            earthly --version
      - checkout
      - run:
          name: build and run dredd
          command: |
            # mkdir tmp
            docker-compose up
            sleep 15
            earthly --ci +test
            # make db/migrate
            # make test/integration


workflows:
  tests:
    jobs:
      - tests
