version: 2.1

jobs:
  prepare:
    machine: true
    steps:
      - run:
          name: Setup earthly
          command: |
            wget https://github.com/earthly/earthly/releases/download/v0.6.1/earthly-linux-amd64 -O /tmp/earthly
            chmod +x /tmp/earthly
            /tmp/earthly bootstrap
            /tmp/earthly --version
      - persist_to_workspace:
          root: /tmp
          paths:
            - earthly

  unit-test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run: /tmp/earthly +unit-test

  integration-test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Docker login"
          command: docker login --username "izumisy" --password "$DOCKERHUB_TOKEN"
      - checkout
      - run: /tmp/earthly -P --ci --push +integration-test

workflows:
  tests:
    jobs:
      - prepare
      - unit-test:
          requires:
            - prepare
      - integration-test:
          requires:
            - prepare
          filters:
            branches:
              only:
                - master
