version: 2.1
jobs:
  tests:
    machine:
      image: ubuntu:latest
      docker_layer_caching: true
    steps:
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Setup earthly
          command: |
            sudo wget https://github.com/earthly/earthly/releases/download/v0.6.1/earthly-linux-amd64 -O /usr/local/bin/earthly
            sudo chmod +x /usr/local/bin/earthly
            earthly bootstrap
            earthly --version
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            sleep 15
            earthly --use-inline-cache --save-inline-cache +test

workflows:
  tests:
    jobs:
      - tests
