name: ci

on: push

jobs:
  unit-testing:
    name: unit testing
    runs-on: ubuntu-latest
    container: golang:1.19.2-buster
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod
      - run: go test ./...

  integration-testing:
    name: integration testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup earthly
        run: |
          wget https://github.com/earthly/earthly/releases/download/v0.6.26/earthly-linux-amd64 -O /tmp/earthly
          chmod +x /tmp/earthly
          /tmp/earthly bootstrap
          /tmp/earthly --version

      - uses: docker/login-action@v2
        with:
          registry: gchr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
