name: ci

on: push

jobs:
  unit-testing:
    name: unit testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

  integration-testing:
    name: integration testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
